//
//  TextValues.swift
//  InternshipApp
//
//  Created by Artur Nozhenko on 04.07.2024.
//

import Foundation

enum TextValues {
    static let addButtonLabel = "Add Options"
    static let backToLoginLabel = "Back to login"
    static let deleteAccountLabel = "Delete account"
    static let customRoundedRectangleButtonLabelFont = "Saira-Regular"
    static let sairaRegular = "Saira-Regular"
    static let buttonLabelFont = "Saira-Bold"
    static let superManLabel = "SUPERMAN"
    static let superGirlLabel = "SUPERGIRL"
    static let gradientDividerText = "GradientDivider"
    static let customTextFieldText = "CustomTextField"
    static let homeVCTitleLabelFont = "Saira"
    static let signUpButtonText = "Sign Up"
    static let selfMatch = "SELF MATCHES %@"
    static let login = "Log In"
    static let name = "Name"
    static let enterName = "Enter name"
    static let email = "Email"
    static let enterEmail = "Enter email"
    static let password = "Password"
    static let createPassword = "Create password"
    static let confirmPassword = "Confirm Password"
    static let enterPassword = "Enter password"
    static let error = "Error"
    static let male = "male"
    static let female = "female"
    static let users = "users"
    static let userId = "userId"
    static let forgotPassword = "Forgot Password?"
    static let loginButtonText = "Login"
    static let forgotPasswordInstructionLabelText = "Enter the email address associated with your account and we'll send you a form to reset your password."
    static let continueLabel = "Continue"
    static let ok = "Ok"
    static let success = "Success"
    static let successResetMessage = "The form has been sent to your e-mail."
    static let failedResetMessage = "Please check the email you entered. Something seems to be wrong"
    static let cancel = "Cancel"
    static let helveticaNeue = "Helvetica Neue"
    static let profileInstruction = "Select an option to display on the main screen."
    static let addOptions = "Add options"
    static let sairaMedium = "Saira-Medium"
    static let profile = "Profile"
    static let successSavedProfile = "Profile has been saved!"
    static let save = "Save"
    static let select = "Select"
    static let selectOption = "Select Option"
    static let weight = "Weight"
    static let kg = "kg"
    static let cm = "cm"
    static let height = "Height"
    static let textFieldCellReuseID = "TextFieldCell"
    static let optionCellReuseID = "OptionCell"
    static let backToRegister = "Back to register"
    static let sairaBold = "Saira-Bold"
    static let homeReuseID = "HomeCell"
    static let chart = "Chart"
    static let progressChartScreenDateLabelText = "Displaying dynamics relative to data from"
    static let buildingBarAnimation = "bounds.size.height"
    static let positionAnimation = "position.y"
    static let progressVCEmptyStateScreen = "Options are not selected. To display them, add them to your profile."
    static let progressTableViewCellReuseID = "ProgressTableViewCell"
}
